/**
 * This code was generated by v0 by Vercel.
 * @see https://v0.dev/t/tEmWnZUbJky
 */
import { CardHeader, CardContent, Card } from "@/components/ui/card"
import { Label } from "@/components/ui/label"
import { Input } from "@/components/ui/input"
import { Textarea } from "@/components/ui/textarea"
import { Button } from "@/components/ui/button"
import { ResponsiveBar } from "@nivo/bar"
import cadillacImage from "../images/caddy.jpg";
import Image from 'next/image';


export function EmailGenerator() {
  return (
    <div className="p-6 bg-gray-100 font-sans">
      <h1 className="text-4xl font-extrabold mb-4 text-blue-700 uppercase font-light">GM Car Campaign Generator</h1>
      <p className="text-gray-700 dark:text-gray-400 mb-6 font-light">
        Create personalized email campaigns for your customer segments interested in General Motors vehicles.
      </p>
      <Card className="bg-white shadow-md rounded-lg p-6 mb-10">
        <CardHeader className="mb-4">
          <h2 className="text-3xl font-bold text-blue-600 uppercase font-light">Example Email</h2>
          <p className="text-gray-500 dark:text-gray-400 font-light">
            Here&aposs an example of how your personalized email could look.
          </p>
        </CardHeader>
        <CardContent className="space-y-4">
          <p className="text-gray-700 font-light">Subject: Explore More Options with GM</p>
          <p className="text-gray-700 font-light">Dear [Customer Name],</p>
          <p className="text-gray-700 font-light">
            We noticed your recent purchase of a Cadillac. We thought you might be interested in these other GM cars:
          </p>
          <div className="grid grid-cols-1 md:grid-cols-3 gap-4">
            <div>
              <Image
                alt="2023 Chevrolet Corvette"
                className="rounded w-full h-auto"
                height={200}
                src={cadillacImage}
                style={{
                  aspectRatio: "300/200",
                  objectFit: "cover",
                }}
                width={300}
              />
              <h3 className="text-xl font-bold mt-2 text-blue-600 font-light">2023 Chevrolet Corvette</h3>
              <p className="text-gray-700 font-light">
                The Chevrolet Corvette is a classic American sports car. It&aposs a top performer with a sleek design and
                high-quality interior.
              </p>
            </div>
            <div>
              <Image
                alt="2023 Buick Enclave"
                className="rounded w-full h-auto"
                height={200}
                src={cadillacImage}
                style={{
                  aspectRatio: "300/200",
                  objectFit: "cover",
                }}
                width={300}
              />
              <h3 className="text-xl font-bold mt-2 text-blue-600 font-light">2023 Buick Enclave</h3>
              <p className="text-gray-700 font-light">
                The Buick Enclave is a luxury crossover with three rows of seats. It has a quiet, comfortable ride and a
                generous list of standard features.
              </p>
            </div>
            <div>
            <Image
              alt="2023 GMC Sierra"
              className="rounded w-full h-auto"
              height={200}
              src={cadillacImage}
              style={{
                aspectRatio: "300/200",
                objectFit: "cover",
              }}
              width={300}
            />
              <h3 className="text-xl font-bold mt-2 text-blue-600 font-light">2023 GMC Sierra</h3>
              <p className="text-gray-700 font-light">
                The GMC Sierra is a highly capable full-size pickup. It offers a variety of powerful engines and a
                comfortable, upscale interior.
              </p>
            </div>
          </div>
          <p className="text-gray-700 mt-4 font-light">
            Each of these vehicles offers unique features and benefits. We&aposd be happy to provide more details or arrange
            a test drive at your convenience.
          </p>
          <p className="text-gray-700 font-light">Best,</p>
          <p className="text-gray-700 font-light">[Your Name]</p>
        </CardContent>
      </Card>
      <Card className="bg-white shadow-md rounded-lg p-6 mb-10">
        <CardHeader className="mb-4">
          <h2 className="text-3xl font-bold text-blue-600 uppercase font-light">Customer Purchase History</h2>
          <p className="text-gray-500 dark:text-gray-400 font-light">
            Here&aposs a dashboard showing the purchase history for customers who have bought Cadillacs.
          </p>
        </CardHeader>
        <CardContent className="space-y-4">
          <BarChart className="w-full h-[300px]" />
          <div className="mt-4 grid grid-cols-1 md:grid-cols-2 gap-4">
            <div>
              <h3 className="text-xl font-bold text-blue-600 font-light">John Doe</h3>
              <p className="text-gray-700 font-light">2023 Cadillac XT5</p>
              <p className="text-gray-700 font-light">Purchase Date: 25 Nov 2023</p>
            </div>
            <div>
              <h3 className="text-xl font-bold text-blue-600 font-light">Jane Smith</h3>
              <p className="text-gray-700 font-light">2023 Cadillac Escalade</p>
              <p className="text-gray-700 font-light">Purchase Date: 12 Dec 2023</p>
            </div>
          </div>
        </CardContent>
      </Card>
      <Card className="bg-white shadow-md rounded-lg p-6 mb-10">
        <CardHeader className="mb-4">
          <h2 className="text-3xl font-bold text-blue-600 uppercase font-light">Customer Segment</h2>
          <p className="text-gray-500 dark:text-gray-400 font-light">Define your customer segment for this campaign.</p>
        </CardHeader>
        <CardContent className="space-y-4">
          <div className="space-y-2">
            <Label htmlFor="segment-name">Segment Name</Label>
            <Input id="segment-name" placeholder="Enter the segment name" />
          </div>
          <div className="space-y-2">
            <Label htmlFor="segment-description">Segment Description</Label>
            <Textarea className="min-h-[100px]" id="segment-description" placeholder="Describe the customer segment" />
          </div>
        </CardContent>
      </Card>
      <Card className="bg-white shadow-md rounded-lg p-6 mb-10">
        <CardHeader className="mb-4">
          <h2 className="text-3xl font-bold text-blue-600 uppercase font-light">Campaign Details</h2>
          <p className="text-gray-500 dark:text-gray-400 font-light">
            Fill out the details for the campaign you want to generate.
          </p>
        </CardHeader>
        <CardContent className="space-y-4">
          <div className="space-y-2">
            <Label htmlFor="campaign-name">Campaign Name</Label>
            <Input id="campaign-name" placeholder="Enter the campaign name" />
          </div>
          <div className="space-y-2">
            <Label htmlFor="campaign-description">Campaign Description</Label>
            <Textarea className="min-h-[100px]" id="campaign-description" placeholder="Describe the campaign" />
          </div>
          <div className="space-y-2">
            <Label htmlFor="campaign-email-subject">Email Subject</Label>
            <Input id="campaign-email-subject" placeholder="Enter the email subject" />
          </div>
          <div className="space-y-2">
            <Label htmlFor="campaign-email-body">Email Body</Label>
            <Textarea
              className="min-h-[200px]"
              id="campaign-email-body"
              placeholder="Dear [Customer Name], We noticed your recent purchase of a Cadillac. We thought you might be interested in these other GM cars..."
            />
          </div>
        </CardContent>
      </Card>
      <Button className="bg-blue-500 hover:bg-blue-600 text-white py-2 px-4 rounded text-lg font-bold uppercase font-light">
        Generate Campaign
      </Button>
    </div>
  )
}


function BarChart(props: { [key: string]: any }) {
  return (
    <div {...props}>
      <ResponsiveBar
        data={[
          {
            name: "A",
            data: 111,
          },
          {
            name: "B",
            data: 157,
          },
          {
            name: "C",
            data: 129,
          },
          {
            name: "D",
            data: 187,
          },
          {
            name: "E",
            data: 119,
          },
          {
            name: "F",
            data: 22,
          },
          {
            name: "G",
            data: 101,
          },
          {
            name: "H",
            data: 83,
          },
        ]}
        keys={["data"]}
        indexBy="name"
        margin={{ top: 50, right: 50, bottom: 50, left: 60 }}
        padding={0.3}
        valueScale={{ type: "linear" }}
        indexScale={{ type: "band", round: true }}
        colors={{ scheme: "paired" }}
        borderWidth={1}
        borderColor={{
          from: "color",
          modifiers: [["darker", 0.2]],
        }}
        axisTop={null}
        axisRight={null}
        axisBottom={{
          tickSize: 5,
          tickPadding: 5,
          tickRotation: 0,
          legend: "Name",
          legendPosition: "middle",
          legendOffset: 45,
          truncateTickAt: 0,
        }}
        axisLeft={{
          tickSize: 5,
          tickPadding: 5,
          tickRotation: 0,
          legend: "Number",
          legendPosition: "middle",
          legendOffset: -45,
          truncateTickAt: 0,
        }}
        theme={{
          tooltip: {
            container: {
              fontSize: "12px",
            },
          },
        }}
        labelSkipWidth={12}
        labelSkipHeight={12}
        role="application"
        ariaLabel="A bar chart showing data"
      />
    </div>
  )
}
